spring:
  datasource:
    url: 'jdbc:h2:mem:todolist'
    driveClassName: org.h2.Driver
    username: admin
    password: admin
  jpa:
    database-plataform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true